import type { Metadata } from "next";
import { Fraunces, Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import SectionReveal from "@/components/SectionReveal";
import SiteFooter from "@/components/SiteFooter";
import WhatsappFab from "@/components/WhatsappFab";
import { site, SITE_URL } from "@/lib/site";
import "./globals.css";

/* Self-hosted at build time by next/font — no runtime request to Google.

   Fraunces is variable: requesting only the opsz axis leaves WONK and SOFT
   pinned at their defaults of 0, which is what DESIGN_BRIEF.md §3.2 asks for.
   No weight is given, so the full 100–900 range ships and the type scale can
   use 400 for display and 500 for H3. */
const fraunces = Fraunces({
  subsets: ["latin"],
  axes: ["opsz"],
  display: "swap",
  variable: "--font-fraunces",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

/* SEO — DESIGN_BRIEF.md §6, Phase 12.

   metadataBase makes every relative URL below absolute. It resolves from
   NEXT_PUBLIC_SITE_URL; see lib/site.ts for why the localhost fallback must
   not reach production.

   The OG image is generated by app/opengraph-image.tsx — Next discovers that
   file by convention, so it is deliberately not listed here. Phase 14 should
   replace it with the real hero photograph. */
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: site.seo.title,
    template: `%s — ${site.name}`,
  },
  description: site.seo.description,
  applicationName: site.name,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName: site.name,
    title: site.seo.title,
    description: site.seo.description,
    url: "/",
    locale: "en_IN",
  },
  twitter: {
    card: "summary_large_image",
    title: site.seo.title,
    description: site.seo.description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  formatDetection: { telephone: true },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  /* suppressHydrationWarning on <html> is required, not cosmetic: the inline
     script at the top of <body> stamps data-reveal-armed onto <html> before
     React hydrates, so the server HTML and the client tree legitimately differ
     by that one attribute. Without it React logs a hydration mismatch. It
     suppresses the warning for that element's own attributes only. */
  return (
    <html
      lang="en-IN"
      className={`${fraunces.variable} ${inter.variable}`}
      suppressHydrationWarning
    >
      <body>
        {/* Arms the §3.7 reveal before anything below is painted, so there is
            no flash of hidden-then-shown content. Deliberately a blocking
            inline script and not an effect: if it never runs — JS disabled,
            blocked, or failed — the CSS hides nothing and the page renders in
            full. Content visible always beats content animated. */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "document.documentElement.setAttribute('data-reveal-armed','')",
          }}
        />

        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:left-3 focus:top-2 focus:z-50 focus:rounded focus:bg-accent focus:px-2 focus:py-1 focus:text-bg"
        >
          Skip to content
        </a>

        <header>
          <Navbar />
        </header>

        <main id="main">{children}</main>

        <SectionReveal />

        <footer>
          <SiteFooter />
        </footer>

        {/* Outside <main> and <footer>: it is a persistent utility, not part
            of the document's content structure. */}
        <WhatsappFab />
      </body>
    </html>
  );
}
