export interface Product {
  id: string;
  code: string;
  name: string;
  category: "plain-towels" | "checked-towels" | "white-towels" | "kora-towels" | string;
  categoryLabel: string;
  badge?: string;
  shortDescription: string;
  fullDescription: string;
  gsm: string;
  gsmValue: number;
  dimensions: string;
  blend: string;
  weaveType: string;
  colors: string[];
  moq: string;
  dispatchTime: string;
  image: string;
  alt: string;
  features: string[];
}

export interface ProductCategory {
  id: string;
  label: string;
  description: string;
  count?: number;
}

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  {
    id: "all",
    label: "All Products",
    description: "Complete catalogue of handloom cotton blend towels and institutional textiles.",
  },
  {
    id: "plain-towels",
    label: "Plain Towels",
    description: "Vibrant solid colorways and dual-color bath towels with uniform absorbency.",
  },
  {
    id: "checked-towels",
    label: "Checked Towels",
    description: "Authentic South Indian handloom check and border patterns woven for durability.",
  },
  {
    id: "white-towels",
    label: "White Towels",
    description: "Bleach-safe optical white bath towels built for hotels, hospitals, and daily wholesale.",
  },
  {
    id: "kora-towels",
    label: "Kora Towels",
    description: "Traditional unbleached kora cotton bath towels in generous dimensions.",
  },
];

export const PRODUCTS_CATALOG: Product[] = [
  // =========================================================================
  // 1. PLAIN TOWELS (7 Products)
  // =========================================================================
  {
    id: "73x146-plain-color-bath-towel",
    code: "SMT-PL-73146",
    name: "73 × 146 Plain Color Bath Towel",
    category: "plain-towels",
    categoryLabel: "Plain Towels",
    badge: "POPULAR",
    shortDescription:
      "Soft, fast-drying plain dyed cotton blend bath towel with reinforced edges and vibrant vat-dyed tones.",
    fullDescription:
      "Woven on traditional handlooms in Pallagoundanpalayam using durable cotton-blend yarn. Retains loft and vibrant colour across commercial wash cycles. Ideal for wholesale merchants, general trade, and institutional supply.",
    gsm: "400 GSM",
    gsmValue: 400,
    dimensions: "26 × 52 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Terry weave with reinforced selvedge",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-plain.jpg",
    alt: "73 x 146 Plain Color Bath Towel by Sri Maruthi Textiles",
    features: [
      "Direct mill wholesale rate",
      "Even selvedges without loose threads",
      "Color-fast vat dyed yarn",
      "Ideal for general trade wholesalers",
    ],
  },
  {
    id: "45x90-plain-color-bath-towel",
    code: "SMT-PL-4590",
    name: "45 × 90 Plain Color Bath Towel",
    category: "plain-towels",
    categoryLabel: "Plain Towels",
    shortDescription:
      "Compact, practical plain color bath towel designed for daily utility, fast turnover, and quick drying.",
    fullDescription:
      "A reliable daily-use size crafted for maximum packing density and rapid drying. Firm looped pile resists snagging and maintains shape through regular commercial washings.",
    gsm: "360 GSM",
    gsmValue: 360,
    dimensions: "22 × 44 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Tight loop terry weave",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/products/bath-towels.jpg",
    alt: "45 x 90 Plain Color Bath Towel by Sri Maruthi Textiles",
    features: [
      "High absorption with quick-dry pile",
      "Locked selvedges for extended longevity",
      "Uniform pile height across entire surface",
      "Direct mill dispatch across TN and Kerala",
    ],
  },
  {
    id: "70-plain-color-bath-towel",
    code: "SMT-PL-70",
    name: "70 Plain Color Bath Towel",
    category: "plain-towels",
    categoryLabel: "Plain Towels",
    shortDescription:
      "Mid-size everyday plain bath towel available in 7 bright, colorfast shades including violet.",
    fullDescription:
      "Engineered for regional retailers and institutional distributors. Provides generous drying surface, balanced fabric weight, and excellent softness against the skin.",
    gsm: "380 GSM",
    gsmValue: 380,
    dimensions: "24 × 48 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Terry weave with sturdy flat border",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue", "Violet"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/custom/waffle-color-stack.jpg",
    alt: "70 Plain Color Bath Towel by Sri Maruthi Textiles",
    features: [
      "Rich 7-color palette including Violet",
      "Tested for commercial colorfastness",
      "Double-stitched end hems",
      "Consistent mill-standard dimensions",
    ],
  },
  {
    id: "90-plain-color-bath-towel",
    code: "SMT-PL-90",
    name: "90 Plain Color Bath Towel",
    category: "plain-towels",
    categoryLabel: "Plain Towels",
    badge: "FAST SELLER",
    shortDescription:
      "Generous 26 × 52 inch plain dyed bath towel with rich color saturation and soft looped terry.",
    fullDescription:
      "One of our most popular running items among wholesale merchants in Kerala and Tamil Nadu. Balanced GSM provides substantial body without excessive laundering weight.",
    gsm: "400 GSM",
    gsmValue: 400,
    dimensions: "26 × 52 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Plush dual-sided terry pile",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue", "Violet"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/custom/custom-towels-palette.jpg",
    alt: "90 Plain Color Bath Towel by Sri Maruthi Textiles",
    features: [
      "Substantial hand feel and great absorbency",
      "Vat-dyed yarns preserve vibrant tones",
      "Reinforced selvedges without loose ends",
      "Ready stock for fast bulk dispatch",
    ],
  },
  {
    id: "16001-plain-color-bath-towel",
    code: "SMT-PL-16001",
    name: "16001 Plain Color Bath Towel",
    category: "plain-towels",
    categoryLabel: "Plain Towels",
    shortDescription:
      "Premium large-format plain color bath towel crafted for full body coverage and extra absorbency.",
    fullDescription:
      "Designed with an expansive 27 × 54 inch profile and higher yarn density. Delivers exceptional drying comfort, enduring durability, and superior dimensional stability.",
    gsm: "420 GSM",
    gsmValue: 420,
    dimensions: "27 × 54 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "High-density looped terry",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue", "Violet"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/custom/textile-swatches-flatlay.jpg",
    alt: "16001 Plain Color Bath Towel by Sri Maruthi Textiles",
    features: [
      "Large 27 × 54 inch wrap-around size",
      "High loop density for maximum water absorption",
      "Soft textured finish comfortable for daily use",
      "Strict mill quality check before packing",
    ],
  },
  {
    id: "18001-plain-color-bath-towel",
    code: "SMT-PL-18001",
    name: "18001 Plain Color Bath Towel",
    category: "plain-towels",
    categoryLabel: "Plain Towels",
    badge: "EXTRA LARGE",
    shortDescription:
      "Extra-large 31 × 62 inch heavyweight plain towel offering maximum wrap, warmth, and plush comfort.",
    fullDescription:
      "Our largest plain towel offering, woven for customers seeking luxury coverage and high absorbency. Ample 31 × 62 inch footprint makes it ideal for hotels, guest houses, and home linen collections.",
    gsm: "450 GSM",
    gsmValue: 450,
    dimensions: "31 × 62 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Heavyweight terry weave",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-plain.jpg",
    alt: "18001 Plain Color Bath Towel by Sri Maruthi Textiles",
    features: [
      "Expansive 31 × 62 inch extra-large dimensions",
      "Thick pile with superior moisture retention",
      "Stout border construction resists fraying",
      "Bulk packing available in assorted color bales",
    ],
  },
  {
    id: "190-double-color-bath-towel",
    code: "SMT-PL-190",
    name: "190 Double Color Bath Towel",
    category: "plain-towels",
    categoryLabel: "Plain Towels",
    badge: "DUAL COLOR",
    shortDescription:
      "Distinctive double-tone dyed bath towel in an extra-large 31 × 62 inch size with eye-catching contrast.",
    fullDescription:
      "Features an eye-catching double-color woven effect that provides premium visual interest on store shelves. Combines two complementary yarn shades with the strength and resilience of our 80/20 cotton blend.",
    gsm: "450 GSM",
    gsmValue: 450,
    dimensions: "31 × 62 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Dual-tone terry weave",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/products/bath-towels.jpg",
    alt: "190 Double Color Bath Towel by Sri Maruthi Textiles",
    features: [
      "Unique dual-tone woven styling",
      "Extra-large 31 × 62 inch coverage",
      "Color-locked yarns that resist fading",
      "Direct mill wholesale supply",
    ],
  },

  // =========================================================================
  // 2. CHECKED TOWELS (13 Products)
  // =========================================================================
  {
    id: "222-checked-bath-towel",
    code: "SMT-CK-222",
    name: "222 Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    shortDescription:
      "Classic handloom check pattern bath towel in compact 22 × 44 inch size with fast-drying loops.",
    fullDescription:
      "Traditional check design woven with heritage yarn techniques in Pallagoundanpalayam. Durable, quick-drying, and priced for rapid commercial retail turnover.",
    gsm: "350 GSM",
    gsmValue: 350,
    dimensions: "22 × 44 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Traditional checked handloom weave",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-checked.jpg",
    alt: "222 Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Authentic South Indian checked pattern",
      "Clean selvages with minimal yarn distortion",
      "Fast drying lightweight construction",
      "Competitive wholesale pricing per dozen",
    ],
  },
  {
    id: "888-checked-bath-towel",
    code: "SMT-CK-888",
    name: "888 Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    badge: "BESTSELLER",
    shortDescription:
      "Popular 24 × 48 inch checked towel with vibrant contrast yarns and high absorbency.",
    fullDescription:
      "A long-standing favorite across wholesale markets in Ernakulam, Kozhikode, and Coimbatore. Features crisp check definition with uniform yarn tension throughout the fabric.",
    gsm: "380 GSM",
    gsmValue: 380,
    dimensions: "24 × 48 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Checked terry weave with selvedges",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/products/madras-check-towels.jpg",
    alt: "888 Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Consistent high-selling running item",
      "Crisp square check alignment",
      "Pre-tested against yarn bleeding",
      "Ready stock for bulk wholesale dispatch",
    ],
  },
  {
    id: "555-checked-bath-towel",
    code: "SMT-CK-555",
    name: "555 Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    shortDescription:
      "Heritage 4-color checked bath towel crafted for reliable everyday performance and durability.",
    fullDescription:
      "Woven in core classic colorways: Red, Maroon, Olive Green, and Navy Blue. Balances soft absorption with handloom resilience for institutional hostels and textile retailers.",
    gsm: "380 GSM",
    gsmValue: 380,
    dimensions: "24 × 48 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Classic yarn-dyed check weave",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/sample-kit/sample-check-weave.png",
    alt: "555 Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Timeless heritage South Indian design",
      "Strong yarn twist prevents linting",
      "Even selvedges without loose ends",
      "Direct mill wholesale rate",
    ],
  },
  {
    id: "10001-checked-bath-towel",
    code: "SMT-CK-10001",
    name: "10001 Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    shortDescription:
      "Fine-density checked bath towel in standard 24 × 48 inch dimensions with sharp grid lines.",
    fullDescription:
      "Crafted with fine-count warp and weft yarns for a smoother feel and sharper check geometry. Highly absorbent, shrink-resistant, and machine-wash safe.",
    gsm: "390 GSM",
    gsmValue: 390,
    dimensions: "24 × 48 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Fine checked terry weave",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-checked.jpg",
    alt: "10001 Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Refined fine-grid check appearance",
      "Excellent moisture retention capacity",
      "Tight side selvedges prevent unraveling",
      "Direct mill supply from Tiruppur district",
    ],
  },
  {
    id: "175-checked-bath-towel",
    code: "SMT-CK-175",
    name: "175 Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    shortDescription:
      "Spacious 27 × 54 inch checked towel built for comfortable full body drying and daily retail demand.",
    fullDescription:
      "A generous bath towel size featuring our signature yarn-dyed checks. Ideal for family retail trade and hospitality linen counters across South India.",
    gsm: "410 GSM",
    gsmValue: 410,
    dimensions: "27 × 54 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Checked terry with reinforced border",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/products/madras-check-towels.jpg",
    alt: "175 Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Generous 27 × 54 inch coverage",
      "Vibrant multi-color check options",
      "Durable loop structure resists flattening",
      "Strict quality inspection per lot",
    ],
  },
  {
    id: "15001-checked-bath-towel",
    code: "SMT-CK-15001",
    name: "15001 Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    badge: "PREMIUM WEAVE",
    shortDescription:
      "Large 28 × 56 inch checked towel with high yarn count, dense terry loop, and superior bulk.",
    fullDescription:
      "Premium checked specification towel offering superior bulk and plushness. Built to withstand commercial laundry cycles while maintaining its shape and vibrant check definition.",
    gsm: "430 GSM",
    gsmValue: 430,
    dimensions: "28 × 56 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Dense checked terry pile",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/sample-kit/sample-check-weave.png",
    alt: "15001 Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Substantial 28 × 56 inch bath sheet size",
      "Dense loop pile for rapid drying action",
      "Hemmed with high-tensile poly-cotton thread",
      "Ideal for premium linen retailers",
    ],
  },
  {
    id: "120-checked-bath-towel",
    code: "SMT-CK-120",
    name: "120 Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    shortDescription:
      "Mid-heavy checked bath towel with crisp square patterning in 27 × 54 inch dimensions.",
    fullDescription:
      "Engineered for durability and ease of maintenance. Features balanced warp and weft counts that minimize bowing or warping after commercial wash.",
    gsm: "410 GSM",
    gsmValue: 410,
    dimensions: "27 × 54 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Traditional checked terry weave",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-checked.jpg",
    alt: "120 Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Balanced 80/20 cotton blend composition",
      "Vat-dyed yarns with high wash fastness",
      "Reinforced selvedges without loose threads",
      "Direct mill pricing",
    ],
  },
  {
    id: "150-checked-bath-towel",
    code: "SMT-CK-150",
    name: "150 Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    shortDescription:
      "27 × 54 inch checked towel with classic weave and reliable absorbency for bulk buyers.",
    fullDescription:
      "A trusted wholesale running item with proven market acceptance. Soft to the touch, quick to absorb moisture, and easy to wash.",
    gsm: "410 GSM",
    gsmValue: 410,
    dimensions: "27 × 54 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Checked terry weave",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/products/madras-check-towels.jpg",
    alt: "150 Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Consistent handloom quality assurance",
      "Clean hems with double-needle lockstitch",
      "6 bright color options for retail assortment",
      "Fast mill dispatch",
    ],
  },
  {
    id: "12001-checked-bath-towel",
    code: "SMT-CK-12001",
    name: "12001 Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    shortDescription:
      "26 × 52 inch checked bath towel balancing comfort, strength, and quick drying.",
    fullDescription:
      "Woven on robust looms in Pallagoundanpalayam with uniform yarn tension. Offers an ideal combination of softness and institutional longevity.",
    gsm: "400 GSM",
    gsmValue: 400,
    dimensions: "26 × 52 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Checked terry weave with selvedges",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/sample-kit/sample-check-weave.png",
    alt: "12001 Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Even selvedges without loose threads",
      "Color-fast vat dyed check yarns",
      "Resistant to out-of-square shrinkage",
      "Bulk bales ready for shipment",
    ],
  },
  {
    id: "30x60-nis-checked-bath-towel",
    code: "SMT-CK-3060NIS",
    name: "30 × 60 NIS Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    shortDescription:
      "Special weave NIS checked bath towel in 26 × 52 inch size with refined border bands.",
    fullDescription:
      "Features an exclusive NIS checked pattern variation with refined border bands. High absorption, low linting, and tested for commercial wash durability.",
    gsm: "400 GSM",
    gsmValue: 400,
    dimensions: "26 × 52 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "NIS patterned check weave",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-checked.jpg",
    alt: "30 x 60 NIS Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Distinctive NIS check weave styling",
      "High loop density for swift water uptake",
      "Clean locked side edges",
      "Direct mill wholesale rate",
    ],
  },
  {
    id: "18001-checked-bath-towel",
    code: "SMT-CK-18001",
    name: "18001 Checked Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    badge: "EXTRA LARGE",
    shortDescription:
      "Extra-large 31 × 62 inch checked bath towel providing luxurious wrap, warmth, and full coverage.",
    fullDescription:
      "Our largest checked towel, crafted for customers who demand superior size and premium drying comfort. Features our classic checked motif across an expansive 31 × 62 inch canvas.",
    gsm: "450 GSM",
    gsmValue: 450,
    dimensions: "31 × 62 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Heavyweight checked terry weave",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/products/madras-check-towels.jpg",
    alt: "18001 Checked Bath Towel by Sri Maruthi Textiles",
    features: [
      "Expansive 31 × 62 inch full-body coverage",
      "Heavyweight terry pile for high water capacity",
      "Rich color saturation across all check tones",
      "Factory packed in wholesale bales",
    ],
  },
  {
    id: "30x60-black-bath-towel",
    code: "SMT-CK-3060BK",
    name: "30 × 60 Black Border Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    shortDescription:
      "Distinctive black accent border checked bath towel in 25 × 52 inch size.",
    fullDescription:
      "Incorporates deep black contrast border yarns with our vibrant checked body weave. Sharp aesthetic that stands out on retail racks and linen shelves.",
    gsm: "390 GSM",
    gsmValue: 390,
    dimensions: "25 × 52 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Checked weave with black accent border",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/sample-kit/sample-check-weave.png",
    alt: "30 x 60 Black Border Bath Towel by Sri Maruthi Textiles",
    features: [
      "Deep black contrast border styling",
      "Vat-dyed yarns that retain sharp lines",
      "Double-stitched selvedge hems",
      "Direct mill pricing",
    ],
  },
  {
    id: "70x140-black-bath-towel",
    code: "SMT-CK-70140BK",
    name: "70 × 140 Black Border Bath Towel",
    category: "checked-towels",
    categoryLabel: "Checked Towels",
    badge: "MODERN CONTRAST",
    shortDescription:
      "Large 28 × 56 inch checked bath towel with bold black accent border framing.",
    fullDescription:
      "Combines an expansive 28 × 56 inch towel footprint with striking black border yarns. High absorbent pile delivers both visual elegance and long-lasting commercial utility.",
    gsm: "430 GSM",
    gsmValue: 430,
    dimensions: "28 × 56 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Dense checked weave with black selvedge",
    colors: ["Red", "Maroon", "Olive Green", "Navy Blue", "Cyan", "Blue"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-checked.jpg",
    alt: "70 x 140 Black Border Bath Towel by Sri Maruthi Textiles",
    features: [
      "Large 28 × 56 inch generous size",
      "Bold black accent frame detailing",
      "Commercial laundry tested durability",
      "Available for immediate bulk dispatch",
    ],
  },

  // =========================================================================
  // 3. WHITE TOWELS (8 Products)
  // =========================================================================
  {
    id: "20x40-white-bath-towel",
    code: "SMT-WH-2040",
    name: "20 × 40 White Bath Towel",
    category: "white-towels",
    categoryLabel: "White Towels",
    shortDescription:
      "Compact optical white bath towel ideal for hospital wards, spas, salons, and clinics.",
    fullDescription:
      "Bleach-safe optical white cotton blend towel manufactured for institutions requiring frequent high-temperature wash sanitization. Low lint and rapid drying.",
    gsm: "340 GSM",
    gsmValue: 340,
    dimensions: "20 × 40 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Optical white terry pile",
    colors: ["White"],
    moq: "15 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-white.jpg",
    alt: "20 x 40 White Bath Towel by Sri Maruthi Textiles",
    features: [
      "Bleach-safe optical white finish",
      "High temperature commercial wash ready",
      "Even selvedges without loose threads",
      "Competitive wholesale rate for bulk buyers",
    ],
  },
  {
    id: "23x24-white-bath-towel",
    code: "SMT-WH-2324",
    name: "23 × 24 White Bath Towel",
    category: "white-towels",
    categoryLabel: "White Towels",
    shortDescription:
      "22 × 44 inch pristine white towel tailored for lodge, clinic, spa, and salon usage.",
    fullDescription:
      "A durable 22 × 44 inch white utility towel. Woven with clean cotton blend yarns that maintain brightness and absorbency after repeated commercial laundering.",
    gsm: "360 GSM",
    gsmValue: 360,
    dimensions: "22 × 44 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Uniform white terry weave",
    colors: ["White"],
    moq: "15 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/products/hotel-white-luxury.jpg",
    alt: "23 x 24 White Bath Towel by Sri Maruthi Textiles",
    features: [
      "Clean optical white shade",
      "Durable loop structure resists fraying",
      "Quick drying for fast room turnover",
      "Direct mill wholesale dispatch",
    ],
  },
  {
    id: "25x50-white-bath-towel",
    code: "SMT-WH-2550",
    name: "25 × 50 White Bath Towel",
    category: "white-towels",
    categoryLabel: "White Towels",
    shortDescription:
      "Standard 24 × 48 inch white bath towel widely supplied to hotels, lodges, and guest houses.",
    fullDescription:
      "A core institutional running item. Delivers a soft, absorbent guest experience while standing up to rigorous commercial laundry protocols without yellowing.",
    gsm: "380 GSM",
    gsmValue: 380,
    dimensions: "24 × 48 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Hospitality grade white terry",
    colors: ["White"],
    moq: "15 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/process/step-04-folded-towels.jpg",
    alt: "25 x 50 White Bath Towel by Sri Maruthi Textiles",
    features: [
      "Hotel & institutional grade construction",
      "High water absorbency and plush hand",
      "Lock-stitched hems prevent unravelling",
      "Consistent mill quality lot by lot",
    ],
  },
  {
    id: "27x54-white-bath-towel",
    code: "SMT-WH-2754",
    name: "27 × 54 White Bath Towel",
    category: "white-towels",
    categoryLabel: "White Towels",
    badge: "HOTEL GRADE",
    shortDescription:
      "Mid-large 26 × 52 inch optical white bath towel offering generous comfort and commercial resilience.",
    fullDescription:
      "Preferred by resorts and luxury homestays across Kerala and Tamil Nadu. Balanced 80/20 cotton blend provides luxurious loft while preventing out-of-square shrinkage.",
    gsm: "400 GSM",
    gsmValue: 400,
    dimensions: "26 × 52 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Plush white terry with flatweave hem",
    colors: ["White"],
    moq: "15 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-white.jpg",
    alt: "27 x 54 White Bath Towel by Sri Maruthi Textiles",
    features: [
      "Bright optical white yarn finish",
      "Reinforced double-stitched end hems",
      "Zero yarn slippage or edge fraying",
      "Direct mill pricing for hotels",
    ],
  },
  {
    id: "2001-white-bath-towel",
    code: "SMT-WH-2001",
    name: "2001 White Bath Towel",
    category: "white-towels",
    categoryLabel: "White Towels",
    shortDescription:
      "Special 24 × 50 inch white towel built with high-twist yarn for extra-long service life.",
    fullDescription:
      "Constructed with ring-spun yarns to minimize surface linting and yarn wear during industrial tumbling. Delivers consistent white presentation across 100+ wash cycles.",
    gsm: "390 GSM",
    gsmValue: 390,
    dimensions: "24 × 50 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "High-twist optical white terry",
    colors: ["White"],
    moq: "15 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/products/hotel-white-luxury.jpg",
    alt: "2001 White Bath Towel by Sri Maruthi Textiles",
    features: [
      "Low-lint yarn construction",
      "Withstands repeated bleaching",
      "Even selvedges without loose threads",
      "Bulk institutional packaging",
    ],
  },
  {
    id: "4001-white-bath-towel",
    code: "SMT-WH-4001",
    name: "4001 White Bath Towel",
    category: "white-towels",
    categoryLabel: "White Towels",
    badge: "HEAVYWEIGHT",
    shortDescription:
      "Substantial 28 × 56 inch white bath towel with heavy yarn pile, cloud softness, and premium drape.",
    fullDescription:
      "Heavier weight white towel designed for luxury accommodation, resort suites, and VIP guest rooms. Deep terry pile offers fast drying action and cloud-soft hand feel.",
    gsm: "430 GSM",
    gsmValue: 430,
    dimensions: "28 × 56 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Heavyweight institutional white terry",
    colors: ["White"],
    moq: "15 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/process/step-04-folded-towels.jpg",
    alt: "4001 White Bath Towel by Sri Maruthi Textiles",
    features: [
      "Substantial 28 × 56 inch luxury size",
      "High density loop for maximum absorbency",
      "Commercial laundry tested to 100+ cycles",
      "Direct mill pricing",
    ],
  },
  {
    id: "30x60-white-bath-towel",
    code: "SMT-WH-3060",
    name: "30 × 60 White Bath Towel",
    category: "white-towels",
    categoryLabel: "White Towels",
    shortDescription:
      "Spacious 28 × 56 inch crisp white bath sheet for executive hotels, resorts, and premium bath linen.",
    fullDescription:
      "Engineered to deliver high guest satisfaction with substantial fabric heft and clean aesthetic. Fast water uptake with high dimensional retention.",
    gsm: "430 GSM",
    gsmValue: 430,
    dimensions: "28 × 56 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Plush hospitality white weave",
    colors: ["White"],
    moq: "15 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-white.jpg",
    alt: "30 x 60 White Bath Towel by Sri Maruthi Textiles",
    features: [
      "Extra wide wrap-around surface",
      "Bleach-safe and sanitization ready",
      "Locked selvedges prevent edge fray",
      "Direct mill supply from Tamil Nadu",
    ],
  },
  {
    id: "34x68-white-bath-towel",
    code: "SMT-WH-3468",
    name: "34 × 68 White Bath Towel",
    category: "white-towels",
    categoryLabel: "White Towels",
    badge: "EXTRA LARGE",
    shortDescription:
      "Extra-large 31 × 61 inch luxury white bath sheet for luxury suites, wellness spas, and resorts.",
    fullDescription:
      "Our largest white bath towel offering, built for high-end hospitality suites, resorts, and premium bath linen retailers. Unmatched coverage, warmth, and plushness.",
    gsm: "460 GSM",
    gsmValue: 460,
    dimensions: "31 × 61 inch",
    blend: "80% Cotton / 20% Polyester Blend",
    weaveType: "Super plush white bath sheet terry",
    colors: ["White"],
    moq: "15 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/products/hotel-white-luxury.jpg",
    alt: "34 x 68 White Bath Towel by Sri Maruthi Textiles",
    features: [
      "Expansive 31 × 61 inch luxury bath sheet",
      "Superb water uptake and soft luxury feel",
      "Stout border construction resists distortion",
      "Bulk mill pricing for hospitality buyers",
    ],
  },

  // =========================================================================
  // 4. KORA TOWELS (2 Products)
  // =========================================================================
  {
    id: "18001-print-kora-bath-towel",
    code: "SMT-KR-18001P",
    name: "18001 Print Kora Bath Towel",
    category: "kora-towels",
    categoryLabel: "Kora Towels",
    badge: "PRINTED BORDER",
    shortDescription:
      "Traditional unbleached kora cotton bath towel with decorative print border in 33 × 66 inch size.",
    fullDescription:
      "Woven from authentic unbleached kora cotton yarn with a decorative printed border band. Known for its earthy natural color, high absorbency, and traditional appeal across South India.",
    gsm: "440 GSM",
    gsmValue: 440,
    dimensions: "33 × 66 inch",
    blend: "85% Unbleached Cotton / 15% Polyester",
    weaveType: "Traditional unbleached kora weave with printed border",
    colors: ["Natural Kora"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/product-printed.jpg",
    alt: "18001 Print Kora Bath Towel by Sri Maruthi Textiles",
    features: [
      "Natural unbleached kora cotton yarn",
      "Distinctive traditional print border motif",
      "Expansive 33 × 66 inch South Indian size",
      "Softens with every wash cycle",
    ],
  },
  {
    id: "18001-normal-kora-bath-towel",
    code: "SMT-KR-18001N",
    name: "18001 Normal Kora Bath Towel",
    category: "kora-towels",
    categoryLabel: "Kora Towels",
    badge: "TRADITIONAL",
    shortDescription:
      "Pure classic unbleached kora cotton bath towel in an authentic 33 × 66 inch South Indian size.",
    fullDescription:
      "Pure classic South Indian handloom kora towel with natural unbleached yarn finish and solid border. Excellent everyday absorbency, skin-friendly texture, and long-lasting durability.",
    gsm: "440 GSM",
    gsmValue: 440,
    dimensions: "33 × 66 inch",
    blend: "85% Unbleached Cotton / 15% Polyester",
    weaveType: "Pure traditional kora handloom weave",
    colors: ["Natural Kora"],
    moq: "10 pieces",
    dispatchTime: "1 to 2 days",
    image: "/images/sample-kit/sample-kit-towels.jpg",
    alt: "18001 Normal Kora Bath Towel by Sri Maruthi Textiles",
    features: [
      "100% authentic South Indian kora finish",
      "Generous 33 × 66 inch dimensions",
      "Even selvedges without loose threads",
      "Direct mill wholesale rate",
    ],
  },
];
