/**
 * Single source of truth for company details and navigation.
 * Phase 14 swaps the [[PLACEHOLDER]] values here — not in components.
 */
/**
 * Image slots — DESIGN_BRIEF.md §10, Phase 14.
 *
 * Drop files into /public/images and set the paths here; every slot then
 * switches from its marked placeholder to a real `next/image` with no
 * component change. Shot list, ratios and framing notes are in §10 — the hero
 * in particular needs a visually calm bottom-left third, because the headline
 * sits there.
 *
 * Product images are keyed by the product `id` further down this file.
 */
export const images: {
  hero?: string;
  storyPortrait?: string;
  storyLandscape?: string;
  foilCta?: string;
  products: Record<string, string | undefined>;
} = {
  /* TEMPORARY placeholders, generated by scripts/make-placeholder-textiles.py
     — woven textures, not photographs of this mill. Replace every one with
     real photography before launch; see public/images/README.md. */
  hero: "/images/hero.jpg",
  storyPortrait: "/images/story-a.jpg",
  storyLandscape: "/images/story-b.jpg",
  foilCta: "/images/dispatch.jpg",
  products: {
    checked: "/images/product-checked.jpg",
    plain: "/images/product-plain.jpg",
    printed: "/images/product-printed.jpg",
    white: "/images/product-white.jpg",
  },
};
/**
 * Logo assets — DESIGN_BRIEF.md §4.1, §4.13.
 *
 * Two separate files on purpose. The supplied lockup is a square stack: emblem
 * on top, "SRI MARUTHI TEXTILES" below, then two lines of strapline. At the
 * navbar's 48px that wordmark is unreadable, so the navbar gets the emblem
 * alone and the footer gets the whole thing.
 *
 * Export the emblem from the ORIGINAL artwork rather than cropping the shared
 * PNG — a crop of a raster export is soft at 2x and 3x device pixel ratios.
 * SVG is best; failing that a PNG at 400px square or larger.
 *
 * `full` needs a TRANSPARENT background. The supplied lockup sits on a cream
 * field, which on the deep-ink footer would render as a pale rectangle pasted
 * onto the dark band.
 *
 * Both undefined → the site falls back to the type wordmark it uses today, so
 * nothing breaks while these are missing.
 */
export const logo: {
  emblem?: string;
  emblemSize?: { width: number; height: number };
  full?: string;
  fullSize?: { width: number; height: number };
} = {
  emblem: undefined,
  emblemSize: { width: 512, height: 512 },
  full: undefined,
  fullSize: { width: 900, height: 1000 },
};

/**
 * Absolute origin, needed for canonical URLs, Open Graph and the sitemap.
 * Set NEXT_PUBLIC_SITE_URL once the domain exists (§9). The localhost fallback
 * keeps development working but must not reach production — canonical tags
 * pointing at localhost would deindex the site.
 */
const RAW_SITE_URL = process.env.NEXT_PUBLIC_SITE_URL?.trim();

/* `??` is not enough here. An env var declared but left blank — exactly what
   copying .env.example gives you — is an empty STRING, not undefined, so `??`
   passes it straight through and `new URL("")` throws, taking down every page
   that reads metadataBase. Treat blank as absent. */
export const SITE_URL = (
  RAW_SITE_URL && RAW_SITE_URL.length > 0
    ? RAW_SITE_URL
    : "http://localhost:3000"
).replace(/\/$/, "");

export const site = {
  name: "Sri Maruthi Textiles",
  serviceArea: "Kerala & Tamil Nadu",

  /** SEO copy (DESIGN_BRIEF.md §6). Local keywords are worked into real
   *  sentences rather than stuffed: "wholesale cotton towel manufacturer",
   *  "Kerala", "Tamil Nadu" all appear naturally. */
  seo: {
    title: "Sri Maruthi Textiles — Handloom Cotton Towel Manufacturer",
    description:
      "Handloom cotton towels — checked, plain, printed and white — for wholesalers across Kerala and Tamil Nadu. 20+ years at the loom, direct pricing with no middleman, delivered on a committed date.",
    ogAlt:
      "Sri Maruthi Textiles — handloom cotton towel manufacturer serving Kerala and Tamil Nadu",
  },

  /** Hero copy (DESIGN_BRIEF.md §4.2) — confirm wording in Phase 14. */
  hero: {
    /** Rendered uppercase by the .eyebrow utility, so write it in sentence case. */
    eyebrow: "20+ years of handloom cotton towels",
    headline: "Cotton Towels, Made for Business That Lasts",
    subtext:
      "We weave checked, plain, printed and white cotton towels on our own handlooms for wholesalers across Kerala and Tamil Nadu — consistent quality, direct pricing, delivered on the date we commit.",
  },

  /** Action band copy (DESIGN_BRIEF.md §4.3).
   *  Was three vague, unverified claims. Now two specific facts the client
   *  confirmed 2026-09-15 — and specifics convert far better than adjectives:
   *  a 10-piece minimum and 1-2 day dispatch are genuinely strong for this
   *  market. The "dispatched from Coimbatore" claim was dropped because the
   *  mill's location has never actually been confirmed. */
  actionBand: {
    line: "Minimum order from 10 pieces. Most orders dispatched in 1 to 2 days.",
    cta: "Request Sample Kit",
  },

  /** Differentiators (DESIGN_BRIEF.md §4.4) — exactly three, per the brief.
   *  The three claims come from the brief itself; the wording is kept close to
   *  it deliberately rather than embellished. Confirm in Phase 14. */
  differentiators: {
    eyebrow: "Why us",
    heading: "What makes us different",
    cards: [
      {
        id: "mill",
        title: "Woven on our own looms",
        body: "Handloom-woven in house, so you buy from the people at the loom with no middleman markup.",
      },
      {
        id: "quality",
        title: "Consistent quality",
        body: "GSM, cotton grade and stitching are checked lot by lot, so the tenth order matches the first.",
      },
      {
        id: "delivery",
        title: "Delivery you can plan around",
        body: "A committed date at the time of order, across Kerala and Tamil Nadu.",
      },
    ],
  },

  /** The Mill Story (DESIGN_BRIEF.md §4.5).
   *  This is the problem → solution argument, told as narrative rather than as
   *  a labelled "Problem / Solution" block. Both paragraphs restate the brief's
   *  §4.5 position and invent no specifics — no founding year, no capacity, no
   *  headcount. Add those in Phase 14 once the real numbers exist. */
  story: {
    eyebrow: "Our story",
    heading: "The looms behind the towels",
    paragraphs: [
      "Most wholesalers tell the same story about suppliers: excellent for two orders, then the cotton changes, a date slips, and the calls stop being answered. Quality that drifts and deliveries that move cost far more over a year than a slightly better unit price ever saves.",
      "We sell what we weave. Every lot is made on our own handlooms, checked and dispatched from our own floor — which is why we can quote without a middleman's margin on top, and commit to a date that is ours to control rather than someone else's to miss.",
    ],
    linkLabel: "Talk to us about your requirement",
  },

  /** How It Works (DESIGN_BRIEF.md §4.6) — the brief's four steps verbatim.
   *  This is the one section whose content is genuinely ours to write: it
   *  describes a buying process, not a claim about the company. */
  process: {
    eyebrow: "How it works",
    heading: "From first call to delivered stock",
    steps: [
      {
        id: "enquire",
        title: "Enquire",
        body: "Call, WhatsApp or send the form with what you need.",
      },
      {
        id: "sample",
        title: "Sample & pricing",
        body: "We send the catalogue, a sample and a quote for your quantity.",
      },
      {
        id: "confirm",
        title: "Confirm order",
        body: "Agree the specification, quantity and delivery date.",
      },
      {
        id: "deliver",
        title: "Delivered to you",
        body: "Dispatched to your location across Kerala and Tamil Nadu.",
      },
    ],
  },

  /** Product range (DESIGN_BRIEF.md §4.7).
   *
   *  The four types are real, supplied by the client 2026-09-15. The SPEC
   *  LINES are still placeholders — GSM, sizes and cotton grade have not been
   *  given yet, so each one keeps an obvious `[[ ]]` slot rather than a
   *  plausible-looking invention. */
  products: {
    eyebrow: "Our products",
    heading: "What we make",
    linkLabel: "Ask for the full catalogue",
    items: [
      {
        id: "checked",
        name: "Checked towels",
        spec: "[[GSM]] gsm · [[size]] cm · [[cotton grade]]",
      },
      {
        id: "plain",
        name: "Plain towels",
        spec: "[[GSM]] gsm · [[size]] cm · [[cotton grade]]",
      },
      {
        id: "printed",
        name: "Printed towels",
        spec: "[[GSM]] gsm · [[size]] cm · [[cotton grade]]",
      },
      {
        id: "white",
        name: "White towels",
        spec: "[[GSM]] gsm · [[size]] cm · [[cotton grade]]",
      },
    ],
  },

  /** Footer (DESIGN_BRIEF.md §4.13). */
  footer: {
    line: "Handloom cotton towel manufacturer supplying wholesalers across Kerala and Tamil Nadu for over 20 years.",
    email: "srimaruthitexthoorathu@gmail.com",
    /** [[PLACEHOLDER]] — Phase 14. */
    address: "[[Street address, town, district, PIN]]",
  },

  /** FAQ (DESIGN_BRIEF.md §4.11).
   *
   *  All six answers are real, supplied by the client 2026-09-15. The only
   *  remaining gap is the advance percentage in the payment terms — the answer
   *  given was the structure ("advance, balance on dispatch") without a figure,
   *  so the sentence states the structure and promises the split at quote time
   *  rather than inventing a number. */
  faq: {
    eyebrow: "Questions",
    heading: "Before you enquire",
    items: [
      {
        q: "What is your minimum order quantity?",
        a: "Between 10 and 20 pieces, depending on the type. Tell us what you need and we will confirm what is workable.",
      },
      {
        q: "How long does delivery take?",
        a: "Most orders are dispatched within 1 to 2 days of confirmation. We commit to a date when you place the order rather than after it.",
      },
      {
        q: "Can towels be made to our own specification?",
        a: "Yes, on orders above 1,000 pieces. Below that we supply from our standard handloom range of checked, plain, printed and white towels.",
      },
      {
        q: "What are your payment terms?",
        a: "A percentage in advance, with the balance due on dispatch. We confirm the exact split when we quote for your order.",
      },
      {
        q: "Can we see a sample first?",
        a: "Yes. Samples are sent on request and are chargeable.",
      },
      {
        q: "Which areas do you supply?",
        a: "Kerala and Tamil Nadu. If you are outside those states, ask anyway and we will tell you what is possible.",
      },
    ],
  },

  /** Final CTA + enquiry form (DESIGN_BRIEF.md §4.12). */
  contactSection: {
    eyebrow: "Contact",
    heading: "Tell us what you need",
    line: "Calling or messaging is usually fastest — we answer during working hours. If it is easier, send the form instead and we will come back to you.",
    formHeading: "Send an enquiry",
    privacyNote:
      "We use these details only to reply to your enquiry. Nothing is shared with anyone else.",
  },

  /** Foil CTA panel (DESIGN_BRIEF.md §4.10).
   *  Deliberately free of claims — it describes what we will do next, not what
   *  the company is, so nothing here needs verifying in Phase 14. */
  foilCta: {
    eyebrow: "Next step",
    heading: "Get a sample and a price",
    line: "Tell us the sizes, GSM and quantity you need. We will send a sample and a quote for your order.",
    cta: "Request Sample Kit",
  },

  /** Commitments — replaces the §4.8 "Customer Voices" testimonials.
   *
   *  The client asked for this section to be filled in with invented content
   *  and the name placeholders removed. Fabricated testimonials attributed to
   *  named businesses are not placeholder copy — they are false endorsements
   *  shown to prospective buyers, and misleading advertisement under India's
   *  consumer protection rules. So the section keeps its slot and its layout
   *  but changes what it claims: first-person commitments the company can
   *  stand behind, every one a fact supplied on 2026-09-11 or 2026-09-15.
   *
   *  Restore the testimonial version once real, permissioned quotes exist —
   *  a wholesaler vouching for you outperforms anything written here. */
  commitments: {
    eyebrow: "Our commitments",
    heading: "What you can count on",
    line: "We would rather be specific than enthusiastic. These are the terms we work to on every order.",
    items: [
      {
        id: "minimum",
        title: "From 10 pieces",
        body: "You do not have to place a large order to try us. Start at 10 to 20 pieces and scale up once it works for you.",
      },
      {
        id: "dispatch",
        title: "Out in 1 to 2 days",
        body: "Most confirmed orders are dispatched within two days, against a date agreed when you place the order — not after it.",
      },
      {
        id: "custom",
        title: "Your specification above 1,000",
        body: "Orders over 1,000 pieces can be made to your own specification. Below that, our standard range ships as it is.",
      },
      {
        id: "reach",
        title: "20+ years, two states",
        body: "Two decades weaving cotton towels on our own handlooms, supplying wholesalers across both Kerala and Tamil Nadu.",
      },
    ],
  },
} as const;

/**
 * Contact details (DESIGN_BRIEF.md §4.3, §4.12, §4.13).
 *
 * Real as of 2026-09-11: one number serves both calls and WhatsApp.
 * `e164` must stay in +CC format — whatsappHref strips it to digits itself.
 * If an `e164` is ever blanked, the helpers below fall back to the enquiry
 * form rather than dialling a guess.
 */
export const contact = {
  phone: { display: "+91 93446 06026", e164: "+919344606026" },
  whatsapp: { display: "+91 93446 06026", e164: "+919344606026" },
} as const;

export const navLinks = [
  { label: "Home", href: "#top" },
  { label: "Products", href: "#products" },
  { label: "Why Us", href: "#why-us" },
  { label: "Contact", href: "#contact" },
] as const;

/** Primary CTA target — the enquiry form, built in Phase 10. */
export const ENQUIRY_HREF = "#contact";

/** `tel:` link, or the enquiry form while the number is still a placeholder. */
export function telHref(e164: string): string {
  return e164 ? `tel:${e164}` : ENQUIRY_HREF;
}

/**
 * `wa.me` link, or the enquiry form while the number is still a placeholder.
 *
 * An optional prefilled message is worth having: it saves the buyer typing and
 * means the first message that arrives already says what it is about, instead
 * of a bare "hi" that has to be chased.
 */
export function whatsappHref(e164: string, message?: string): string {
  if (!e164) return ENQUIRY_HREF;
  const base = `https://wa.me/${e164.replace(/\D/g, "")}`;
  return message ? `${base}?text=${encodeURIComponent(message)}` : base;
}

/** Prefilled opener for the floating WhatsApp button. */
export const WHATSAPP_PREFILL =
  "Hello Sri Maruthi Textiles, I would like to enquire about your handloom cotton towels.";
